---
- name: Set package name (Amazon Linux 2)
  ansible.builtin.set_fact:
    vscode_package: "code-1.85.2-1705561377.el7.x86_64"
  when: ansible_distribution == 'Amazon' and ansible_distribution_major_version|int < 2023

- name: Import key (APT)
  ansible.builtin.get_url:
    url: "{{ vscode_mirror }}/keys/microsoft.asc"
    dest: "{{ vscode_keyring }}"
    mode: '0644'
    force: true
  become: true
  when: ansible_os_family == 'Debian'

- name: Disable vscode repository not using keyring (APT)
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] {{ vscode_mirror }}/repos/vscode stable main"
    filename: vscode
    state: absent
  become: true
  when: ansible_os_family == 'Debian'

- name: Enable vscode repository (APT)
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by={{ vscode_keyring }}] {{ vscode_mirror }}/repos/vscode stable main"
    filename: vscode
    state: present
  become: true
  when: ansible_os_family == 'Debian'

- name: Enable vscode repository (Yum)
  ansible.builtin.yum_repository:
    name: vscode
    description: Visual Studio Code repository
    state: present
    baseurl: "{{ vscode_mirror }}/yumrepos/vscode"
    gpgkey: "{{ vscode_mirror }}/keys/microsoft.asc"
    gpgcheck: yes
    includepkgs: code
  become: true
  when: ansible_os_family == 'RedHat'

- name: Install missing package dependencies Debian (gh/ms/vscode/issues/121640)
  ansible.builtin.package:
    name:
      - libxshmfence1
      - libasound2
      - libunwind8
    state: present
  become: true
  when: ansible_os_family == 'Debian'

- name: Install missing package dependencies RedHat (gh/ms/vscode/issues/17142)
  ansible.builtin.package:
    name:
      - libxshmfence
      - libX11-xcb
    state: present
  become: true
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version > '7'

- name: Install vscode
  ansible.builtin.package:
    name: "{{ vscode_package }}"
    state: latest
  become: true

- name: Install extensions
  ansible.builtin.command: "code --install-extension {{ item }}"
  with_items: "{{ vscode_extensions }}"
  register: result
  changed_when: "'already installed' not in result.stdout"
  when: vscode_user | length == 0

- name: Install extensions for vscode_user
  ansible.builtin.command: "code --install-extension {{ item }}"
  with_items: "{{ vscode_extensions }}"
  register: result
  changed_when: "'already installed' not in result.stdout"
  become_user: "{{ vscode_user }}"
  become: true
  when: vscode_user | length > 0
