---
- name: Import key (APT)
  apt_key:
    url: "{{ vscode_mirror }}/keys/microsoft.asc"
    state: present
  become: true
  when: ansible_os_family == 'Debian'

- name: Enable vscode repository (APT)
  apt_repository:
    repo: "deb [arch=amd64] {{ vscode_mirror }}/repos/vscode stable main"
    filename: vscode
    state: present
  become: true
  when: ansible_os_family == 'Debian'

- name: Enable vscode repository (Yum)
  yum_repository:
    name: vscode
    description: Visual Studio Code repository
    state: present
    baseurl: "{{ vscode_mirror }}/yumrepos/vscode"
    gpgkey: "{{ vscode_mirror }}/keys/microsoft.asc"
    gpgcheck: yes
    includepkgs: code
  become: true
  when: ansible_os_family == 'RedHat'

- name: Install missing package dependencies Debian (gh/ms/vscode/issues/121640)
  package:
    name:
      - libxshmfence1
      - libasound2
      - libunwind8
    state: present
  become: true
  when: ansible_os_family == 'Debian'

- name: Install missing package dependencies RedHat (gh/ms/vscode/issues/17142)
  package:
    name:
      - libxshmfence
      - libX11-xcb
    state: present
  become: true
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version > '7'

- name: Install vscode
  package:
    name: code
    state: present
  become: true

- name: Install extensions 
  command: "code --install-extension {{ item }}"
  with_items: "{{ vscode_extensions }}"
  register: result
  changed_when: "'already installed' not in result.stdout"
  when: vscode_user | length == 0

- name: Install extensions for vscode_user
  command: "code --install-extension {{ item }}"
  with_items: "{{ vscode_extensions }}"
  register: result
  changed_when: "'already installed' not in result.stdout"
  become_user: "{{ vscode_user }}"
  become: true
  when: vscode_user | length > 0
