---
- name: Converge
  hosts: all
  vars:
    vscode_user: vscode_user
    vscode_extensions:
      - fortifyvsts.fortify-extension-for-vs-code
      - ms-azuretools.vscode-docker
      - ms-vscode-remote.remote-containers
  tasks:
    - name: Include vscode
      include_role:
        name: "vscode"
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
