---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check binary file
      stat:
        path: /usr/bin/code
      register: bin
    - name: Assert that vscode is installed
      assert:
        that:
          - "bin.stat.exists"
