---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check binary file
      ansible.builtin.stat:
        path: /usr/bin/code
      register: bin
    - name: Assert that vscode is installed
      ansible.builtin.assert:
        that:
          - "bin.stat.exists"
    - name: Get stat location vscode extensions directory
      ansible.builtin.stat:
        path: "/home/vscode_user/.vscode/extensions"
      register: directory
    - name: "Assertions vscode extensions directory"
      ansible.builtin.assert:
        that:
          - "directory.stat.exists"
          - "directory.stat.isdir"
          - "directory.stat.pw_name == 'vscode_user'"
          - "directory.stat.gr_name == 'vscode_user'"
